name: PSTM_HOLSEA
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cartopy==0.21.0
  - matplotlib=3.10.8
  - numpy
  - xarray
  - pandas
  - scipy
  - pytorch=1.11.0
  - tqdm==4.62.3
  - seaborn==0.11.2
  - statsmodels==0.14.0
  - astropy=4.3.1
  - openpyxl
  - jupyter==1.0.0
  - ipywidgets
  - netcdf4
  - ipykernel
  - netcdf4==1.6.5
  - pip==21.2.4
  - pip:
      - pyro-api==0.1.2
      - pyro-ppl==1.8.4
